### ISSUE TITLE
TransException should be public

### ISSUE THREAD

**Issue by janslav** [jbakic/Shielded#10]
User code needs to be able to exclude TransException from its exception handling code, so that the rollback mechanism is not broken. To do that the easiest way is to simply declare "catch (TransException) { throw; }" before handling base Exception, but when its internal it can't be done.

**Comment by janslav** [comment]
I guess the constructor could remain internal so that people don't get ideas ;)

**Comment by jbakic** [comment]
Interesting issue. In most cases, catching the TransException is not a big deal. If your transaction cannot commit, then it will rollback eventually in either case. It is a problem, however, when someone deliberately calls Shield.Rollback. It's currently possible to prevent that rollback by catching the exception... I think you're right, it should go public with an internal constructor, and additionally, the Shield.Rollback call should "taint" the transaction so that it def. does a rollback even if the exception gets caught.

**Comment by janslav** [comment]
unlike other Exceptions, TransException will "fix itself", that's why I want it excluded from general exception handling. It's not (just) about Shielded working or not working correctly :)
