### ISSUE TITLE
.Net core (standard) support

### ISSUE THREAD

**Issue by otabekgb** [jbakic/Shielded#13]
Is there any plan for .Net core (standard) support?

**Comment by jbakic** [comment]
Yes, I'm working on that. In fact, you can find it here: https://github.com/jbakic/Shielded.Gossip -- in the Shielded.Standard folder. (With unit tests in Shielded.Standard.Tests.) It's completely the same library, just targetting .NET Standard 2. I had to remove the proxy class generator feature, because .NET Standard does not support CodeDOM, but the rest is mostly the same, except for a couple of additions and improvements. I think it's definitely safe to use, it's just that right now you'll have to download and build it yourself. A NuGet package will come.

Shielded.Gossip is the distributed version of Shielded, a distributed transactional memory, which should be the next big step for this project. That is still work in progress, needs more testing, definitely more docs (this is the first complaint I get from everyone I ask right now :) ), and the API may still change, since I have to try it out in some real-world-usage projects before I can declare it a 1.0. If you're interested, take a look, and let me know what you think. I'm really interested in feedback at this stage.

Thank you for your interest in Shielded, and I hope it will be helpful on your project!

**Comment by otabekgb** [comment]
I appreciate your long and clear answer. Thank you.

**Comment by jbakic** [comment]
I finally got around to it - Shielded now supports .NET Standard 2.0 as well. The NuGet package has also been updated, version 4.4.8 has just been published, and it includes DLLs for both the full .NET Framework 4, and for .NET Standard 2.0. The only difference between them is that the Std version does not have the proxy subclass generating feature. Closing this issue.
