### ISSUE TITLE
Please support System.Transactions.TransactionScope

### ISSUE THREAD

**Issue by AceHack** [jbakic/Shielded#17]
They are in .NET standard 2.0

**Comment by jbakic** [comment]
Hello! I think it's best not to do that. Shielded repeats transaction runs in case they fail, restarting the transactional delegate from the beginning. This is difficult to square with TransactionScope, which does nothing like that. It would be possible, but it would be dangerous. The user should be very careful not to run more than one Shielded transaction inside the TransactionScope. A second one cannot merge with the first, already checked Shielded transaction, and trying to run a separate Shielded transaction would easily deadlock with the first one. Easy nestability, the big plus of STM, is out the window. Due to these dangers, supporting TransactionScope out of the box would send the wrong message to library users.

On the other hand, using RunToCommit you can combine Shielded with TransactionScope if you really need to, by doing it explicitly. The general structure to achieve this would be something like:

```csharp
IDisposable shieldedTrans = null;
try
{
    using (var scope = new TransactionScope())
    {
        // ...other transactional stuff here?
        shieldedTrans = Shield.RunToCommit(Timeout.Infinite, SomeDelegate);
        // ...other transactional stuff here?
        scope.Complete();
        shieldedTrans.Commit();
    }
}
finally
{
    if (shieldedTrans != null && !shieldedTrans.Completed)
        shieldedTrans.TryRollback();
}
```

This can be made even simpler in some cases. It is better like this because it forces you to think about how to best organize the interaction between Shielded and TransactionScope transactions, and I believe it makes the dangers more explicit. Implicitly supporting TransactionScope would allow developers to shot themselves in the foot too easily.
