### ISSUE TITLE
MongoDB Deserialization

### ISSUE THREAD

**Issue by thenaka** [jbakic/Shielded#2]
We have an object with a status property that is Shielded. When the object is created we set a Shielded.Conditional, triggered when the status is changed, that writes a history record and publishes the status on an observable. This works fine until we read this object from our MongoDB.

When the object is deserialized and reinstantiated from our MongoDB something happens when the object is created that breaks the Shielded.Conditional. The Shielded.Conitional never fires on this object. We actually have to create another new instance of the object using the properties from the one read from the database to get the Shielded.Conditional callback to work.

**Comment by jbakic** [comment]
Hello!

I'm not sure if I understood your case fully, but I have some idea what might be going on.

Internally, the Shield.Conditional will get registered into a dictionary. The key will be an IShielded reference - the reference to your Shielded status. When you deserialize an object from MongoDB, this will create a new Shielded object, which gets a different reference.

In short, your deserialization method should also register this same Conditional for the newly deserialized object. Also bear in mind that the Conditional registration is holding a reference to your object (or, at least to the Shielded field), so if you ever release these objects to the GC, make sure to dispose of the Conditional (using the IDisposable returned from that method). You might do that in a Dispose method of the object containing the Shielded status field, or, I presume you have some kind of container for all these objects? Such a container can then probably take care of this housekeeping.

In a future version of Shielded I plan to introduce stronger support for backing storage, and along with that for conditional transactions which could get triggered based on the *type* of object which changed, not just based on references to specific instances. This will probably make your use case much simpler. I cannot promise any deadline, of course.

I hope this helps. If not, I would ask you to give a couple of code samples (the object, creation, Conditional, de/serialization). Or perhaps create some minimal project which reproduces the issue.

Thanks for using the library! I hope you're otherwise satisfied.

**Comment by jbakic** [comment]
If this is now resolved, I would kindly ask you to close the issue. If not, then please leave a message, otherwise I will assume it is resolved and close it in a couple of days, to avoid leaving it open indefinitely.

**Comment by thenaka** [comment]
Thank you for your quick reply. After further investigation we found this was an issue with how we were handling the object when we deserialized it, not a problem with Shielded.
