### ISSUE TITLE
Question: Is Commute suitable for lock-free update of immutable tree?

### ISSUE THREAD

**Issue by dadhi** [jbakic/Shielded#5]
var empty = MyTree<K, V>.Empty;
    var t = new Shielded<MyTree<K, V>(empty);
    t.Commute ... ?

**Comment by jbakic** [comment]
Hi! I'm not really sure what you mean. Do you plan to execute other ops together with these commutes in one transaction? Do you care about the "old" value of the tree when updating it?

Generally, a commute is slower than a regular update, but it makes transactions overall faster by reducing their number of conflicts. If your transaction will only read and write over that one field, the Shielded<MyTree<,>>, then you may as well leave it as a normal op, it will be faster that way. You gain the best advantage from commutes when you're doing bigger transactions, and some operations are done as commutes (the ones that are really commutable, of course). Then a conflict over those fields will not cause the entire transaction to repeat, but rather just the commutes, saving some time. This means that it is generally desirable for the commutes to be smaller/faster than the rest of the transaction. However, the commutes are not done under any lock, so, if it makes sense, you may put a bigger operation into them, like a tree update. That's fine.

The most important thing is that the op itself must be commutable, i.e. if their order gets mixed up, the total end effect must be the same.

But, what do you mean by lock-free updates? Internally, Shielded uses a global lock before writing to check the versions of all affected fields, to make sure it is safe to commit your transaction. Both regular operations and commutes equally go through this check, and must pass it, or they will get repeated. With commutes, the only diff is that the whole transaction does not need to repeat, but just the commutable parts.

I hope this was helpful, although my answer is pretty generic. If you'd like, please give me some specific examples of how you were planning to do your transactions, what kind of operations you will do over that tree, and what exactly you want to achieve when you say lock-free. I hope I can give you a more specific answer then.

**Comment by dadhi** [comment]
I mean when for instance adding new key and value into immutable tree, producing new tree. So I do care about previous tree value, and want to retry if tree reference is changed in the middle. Assume that tree is stored in a field. 

If don't care about other fields except the tree, can it be done without lock?

**Comment by dadhi** [comment]
Generally I want to have the max performant version of update, hence without lock, if I don't care about other things except the updated reference.

**Comment by jbakic** [comment]
I'm afraid not, the lock is needed. If you're just changing the tree and nothing else, it's better to do it as normal ops, not commutes, it will be faster. But it will have to check the versions, and this happens under lock.

If you're only working with the tree, then a better way is to just use a standard Interlocked.CompareExchange loop for updates. That's as fast as it gets, and no locks are needed. The only problem is if you sometimes want to use the tree in a bigger transaction with other fields. The CompareExchange loop will not be in sync with other transactional operations, and you may see inconsistency there. Depending on the logic of your domain, perhaps this can work as well, but it is trickier to do correctly and safely. I would recommend the CompareExchange loop if the use of the tree is simple, and normal transactional operations (not commutes) if you sometimes use the tree in bigger transactions and consistency is important.

I'm thinking about adding support to the library for out-of-transaction writes (which are basically micro-transactions, since every write must sync nicely with other transactions). That might enable saving a lot of the time spent on initializing the transaction machinery, so it would allow faster writes when writing to only one field. But, I hope you understand, I cannot give any guarantees, and it's not very certain that this would actually improve the speed much, since the lock will still have to be taken for checking safety.

**Comment by dadhi** [comment]
ok, that fine. Thank you for the answer. 

Actually I am already doing CompareExchange in a loop, in my project. Was just interested if Shielded supports such primitive / fast ops, and how it fits into the general STM picture.

**Comment by jbakic** [comment]
OK, glad I could help. Thank you for your interest in Shielded, and best of luck with your project!

**Comment by jbakic** [comment]
P.S. Have you perhaps considered using the ShieldedDict(Nc)? Though it is transactional and will pay the price of the STM mechanism, it's advantage is that it causes no conflicts when transactions are working on different keys. Internally it uses the std .NET ConcurrentDictionary, which is pretty fast. All in all, individual ops would be slower due to the transaction logic, but it does not lose speed as much when a lot of transactions start working on the dictionary in parallel. Perhaps you can try it out if you have the time for an experiment...

**Comment by dadhi** [comment]
If you interested, here is the code I am using: https://gist.github.com/dadhi/8650365

**Comment by dadhi** [comment]
I am using my own Avl tree implementation, which is optimized for max lookup speed: https://gist.github.com/dadhi/95ec36fe4c7cbb996357

The target project is https://bitbucket.org/dadhi/dryioc

**Comment by jbakic** [comment]
I see. The code for the tree is amazingly short, I think I wasted my time on implementing the Red-black tree here in Shielded ;) Cool.

Since you're just using the one ref in that test, STM makes no sense. If you want to have consistency across multiple Refs, you can use Shielded, and then you could write the Swap operation as a commute, but - the getNewValue lambda would not be allowed to access any other Ref. It would throw if someone did that. So it would probably be better as a normal read&write, I don't know... But I guess it doesn't matter, the transaction mechanism is the price to pay in both cases. It's worth it only if the access patterns to the Refs get complex, and maintaining consistency "manually" becomes difficult...

**Comment by dadhi** [comment]
Yeah,  I was struggling some time ago to get transactional consistency across multiple refs, but solved it via restructing the data - getting relevant refs under parent ref / structure.

Regarding the tree, it is a bit cut off on features. No remove for instance, though I did implemented it as exercise :) No IDict implementation as well. Very simple, but very fast. 

Btw, you are free to use the code from gists, if fits.

**Comment by jbakic** [comment]
Thanks! I was thinking about rewriting the ShieldedTreeNc, but I think I will go with a B-Tree to reduce the number of tracked nodes. If I ever find the time to do it... ;)
