### ISSUE TITLE
Custom IShielded implementations

### ISSUE THREAD

**Issue by janslav** [jbakic/Shielded#9]
I understand implementing an IShlielded is not a trivial matter but I don't think it should be internal. When someone does want to choose to implement something, there's no chance currently.

Typically I can imagine wanting to have a complex object shielded as a whole, i.e. if any of its properties is used, it's as if all of properties are used. Similarly, a collection where either any change is done, or none.
At this point these would I guess be possible using several Shieldeds, but it wouldn't be efficient...

If you created an example of a "complex" type with say 2 properties, others could then use it as inspiration for their own implementations...

**Comment by janslav** [comment]
Basically what needs to be done is when reading/writing property A to also automatically enlist property B. Maybe it isn't that hard but it's definitely not obvious :)

**Comment by jbakic** [comment]
That's the default behavior of any proxy class created by the proxy generator (https://github.com/jbakic/Shielded/blob/master/Shielded/ProxyGen/ProxyGen.cs). If you change one property, the entire object enlists in the transaction as a unit. Anything else would make them dangerous to use... You can also do what it does manually - create a Shielded<> wrapping a value type with multiple fields. If you use that as backing storage for public properties, you can control exactly which props are bound. BTW, it's better to use Shielded<>.Modify if the struct gets bigger, it eliminates needless copying of the whole struct.

As for IShielded, it's internal because the lib is very sensitive to the behavior of implementors. If you need to run something in sync with commits, which is I guess the main thing that would enable, you can use Shield.SyncSideEffect, RunToCommit, or WhenCommitting, in that order of preference. And if you need to trigger things, one field causing changes in others, there's Shielded<>.Changed, or Shield.PreCommit, which can trigger based on arbitrary logic. The README lays everything out, and the tests have lots of examples that can be used as a basis for experimenting. You might have to fix them a bit, I use MonoDevelop so they're NUnit. VS will not recognize them by default, I think...

**Comment by janslav** [comment]
Ok, thanks :)
